# Generated by Django 6.0.6 on 2026-07-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='image',
        ),
        migrations.DeleteModel(
            name='text',
        ),
    ]
