# Generated by Django 6.0.6 on 2026-07-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_data_entry_delete_image_delete_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_entry',
            name='unit',
            field=models.CharField(choices=[('unit', 'Unit'), ('kg', 'Kilogram'), ('liter', 'Liter'), ('piece', 'Piece')], default='unit', max_length=50),
        ),
    ]
