# Generated by Django 6.0.6 on 2026-07-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Frozen Foods', 'Frozen Foods'), ('Meat', 'Meat'), ('Bakery', 'Bakery'), ('Household', 'Household'), ('Dry Goods', 'Dry Goods'), ('Clothing', 'Clothing'), ('Snacks', 'Snacks')], default='Uncategorized', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('liter', 'liter'), ('piece', 'piece')], default='pcs', max_length=50),
            preserve_default=False,
        ),
    ]
